name: beetle-actions

on:
  push:
    tags:
      - '*'

jobs:
  beetle-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # required to clone your code
      - name: beetle-actions
        uses: clivern/beetle-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BEETLE_NUMERIC_TAG: true
          BEETLE_WATCH_DEPLOYMENT: true
          BEETLE_API_URL: ${{secrets.BEETLE_API_URL }}
          BEETLE_API_KEY: ${{secrets.BEETLE_API_KEY }}
          BEETLE_CLUSTER_NAME: ${{secrets.BEETLE_CLUSTER_NAME }}
          BEETLE_NAMESPACE_NAME: ${{secrets.BEETLE_NAMESPACE_NAME }}
          BEETLE_APP_ID: ${{secrets.BEETLE_APP_ID }}
          BEETLE_DEPLOYMENT_STRATEGY: ${{secrets.BEETLE_DEPLOYMENT_STRATEGY }}
          BEETLE_MAX_SURGE: ${{secrets.BEETLE_MAX_SURGE }}
          BEETLE_MAX_UNAVAILABLE: ${{secrets.BEETLE_MAX_UNAVAILABLE }}
